server:
  port: ${PORT}

spring:
  application:
    name: spring-security-jwt
  datasource:
    url: ${DB_HOST}
    username: ${USER_DB}
    password: ${PASSWORD_DB}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${JPA_SHOW_SQL}
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO}

jwt:
  secret-key: ${JWT_SECRET_LEY}
  user-generator: ${JWT_USER_GENERATOR}
  time-expiration: ${JWT_TIME_EXPIRATION}

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL}